#ifndef INSTRUCTION_NAMES_H
#define INSTRUCTION_NAMES_H

#include <string>

namespace rail{

    enum InstName{
        ADD_INST,
        SUB_INST,
        SLL_INST,
        SLT_INST,
        SLTU_INST,
        XOR_INST,
        SRL_INST,
        SRA_INST,
        OR_INST,
        AND_INST,
        MUL_INST,
        MULH_INST,
        MULSU_INST,
        MULU_INST,
        DIV_INST,
        DIVU_INST,
        REM_INST,
        REMU_INST,
        ADDW_INST,
        SUBW_INST,
        SLLW_INST,
        SRLW_INST,
        SRAW_INST,
        ADDI_INST,
        SLLI_INST,
        SLTI_INST,
        SLTIU_INST,
        XORI_INST,
        SRLI_INST,
        SRAI_INST,
        ORI_INST,
        ANDI_INST,
        LUI_INST,
        AUIPC_INST,
        LB_INST,
        LH_INST,
        LW_INST,
        LBU_INST,
        LHU_INST,
        SB_INST,
        SH_INST,
        SW_INST,
        BEQ_INST,
        BNE_INST,
        BLT_INST,
        BGE_INST,
        BLTU_INST,
        BGEU_INST,
        JAL_INST,
        JALR_INST,
        
        MULW_INST,
        DIVW_INST,
        DIVUW_INST,
        REMW_INST,
        REMUW_INST,
        
        ADDIW_INST,
        SLLIW_INST,
        SRLIW_INST,
        SRAIW_INST,

        LWU_INST,
        LD_INST,
        SD_INST,

        FENCE_INST,
        ECALL_INST,
        EBREAK_INST,

        LRW_INST,
        SCW_INST,
        AMOSWAPW_INST, 
        AMOADDW_INST,
        AMOXORW_INST,
        AMOANDW_INST,
        AMOORW_INST,
        AMOMINW_INST,
        AMOMAXW_INST,
        AMOMINUW_INST,
        AMOMAXUW_INST,

        LRD_INST,
        SCD_INST,
        AMOSWAPD_INST,
        AMOADDD_INST,
        AMOXORD_INST,
        AMOANDD_INST,
        AMOORD_INST,
        AMOMIND_INST,
        AMOMAXD_INST,
        AMOMINUD_INST,
        AMOMAXUD_INST,

        UNDEF_INST,
    };

    const std::string InstNamesString[] = {
        "ADD",
        "SUB",
        "SLL",
        "SLT",
        "SLTU",
        "XOR",
        "SRL",
        "SRA",
        "OR",
        "AND",
        "MUL",
        "MULH",
        "MULSU",
        "MULU",
        "DIV",
        "DIVU",
        "REM",
        "REMU",
        "ADDW",
        "SUBW",
        "SLLW",
        "SRLW",
        "SRAW",
        "ADDI",
        "SLLI",
        "SLTI",
        "SLTIU",
        "XORI",
        "SRLI",
        "SRAI",
        "ORI",
        "ANDI",
        "LUI",
        "AUIPC",
        "LB",
        "LH",
        "LW",
        "LBU",
        "LHU",
        "SB",
        "SH",
        "SW",
        "BEQ",
        "BNE",
        "BLT",
        "BGE",
        "BLTU",
        "BGEU",
        "JAL",
        "JALR",

        "MULW",
        "DIVW",
        "DIVUW",
        "REMW",
        "REMUW",

        "ADDIW",
        "SLLIW",
        "SRLIW",
        "SRAIW",

        "LWU",
        "LD",
        "SD",

        "FENCE",
        "ECALL",
        "EBREAK",
        
        "LRW",
        "SCW",
        "AMOSWAPW",
        "AMOADDW",
        "AMOXORW",
        "AMOANDW",
        "AMOORW",
        "AMOMINW",
        "AMOMAXW",
        "AMOMINUW",
        "AMOMAXUW",

        "LRD",
        "SCD",
        "AMOSWAPD",
        "AMOADDD",
        "AMOXORD",
        "AMOANDD",
        "AMOORD",
        "AMOMIND",
        "AMOMAXD",
        "AMOMINUD",
        "AMOMAXUD",

        "UNDEF"
    };

}
#endif